from django.urls import include, path
from rest_framework import routers
from . import views


app_name = 'courses'

# Initialize the Django REST framework router
router = routers.DefaultRouter()

# Register viewsets with their corresponding URL patterns
router.register('courses', views.CourseViewSet)  # accessible at /api/courses/
router.register('subjects', views.SubjectViewSet)  # accessible at /api/subjects/

# URL patterns for the courses API
urlpatterns = [
    path('', include(router.urls)),  # all routes generated by the router
]
